development: &defaults
  adapter: postgresql
  encoding: unicode
  database: feedbin_production
  pool: 19
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES'] %>

development:
  <<: *defaults
  database: feedbin_development

test:
  <<: *defaults
  database: feedbin_test
